# Generated by Django 5.0.7 on 2024-08-09 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bpmeasurement',
            name='note',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
