# Generated by Django 5.0.7 on 2024-08-11 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0002_alter_bpmeasurement_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='username',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
