# Generated by Django 5.0.7 on 2024-08-09 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0002_bpmeasurement_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bpmeasurement',
            old_name='diatolic',
            new_name='diastolic',
        ),
        migrations.RenameField(
            model_name='bpmeasurement',
            old_name='testDateTime',
            new_name='measDateTime',
        ),
        migrations.AddField(
            model_name='bpmeasurement',
            name='logDateTime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
